export const LOCATIONS = [
  {
    id: 1,
    title: 'Brandenburg Gate Reflections',
    description: 'Wait for a rain break and frame the columns in shallow puddle mirrors.',
    location: 'Pariser Platz',
    lat: 52.5162,
    lng: 13.3777,
    mood: 'MELANCHOLIC',
    season: 'ALL',
    timeOfDay: 'EVENING',
    weather: 'RAINY',
    commonsQuery: 'Brandenburg Gate Berlin night',
    fallbackImage: 'https://images.unsplash.com/photo-1599424423953-27203673474e?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 2,
    title: 'Tiergarten Canopy Layers',
    description: 'Compress gold leaves with a long lens and isolate a cyclist for scale.',
    location: 'Tiergarten',
    lat: 52.5145,
    lng: 13.3501,
    mood: 'WARM',
    season: 'AUTUMN',
    timeOfDay: 'AFTERNOON',
    weather: 'SUNNY',
    commonsQuery: 'Tiergarten Berlin autumn',
    fallbackImage: 'https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 3,
    title: 'Alexanderplatz Neon Flow',
    description: 'Shoot a long exposure of trams and LED signage for cyberpunk energy.',
    location: 'Alexanderplatz',
    lat: 52.5219,
    lng: 13.4132,
    mood: 'FUTURISTIC',
    season: 'ALL',
    timeOfDay: 'NIGHT',
    weather: 'CLOUDY',
    commonsQuery: 'Alexanderplatz Berlin night',
    fallbackImage: 'https://images.unsplash.com/photo-1560930950-5cc20e80e392?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 4,
    title: 'TV Tower Blossom Frame',
    description: 'Align the tower with spring blooms for a dreamy vertical frame.',
    location: 'Mauerpark',
    lat: 52.5412,
    lng: 13.4026,
    mood: 'ROMANTIC',
    season: 'SPRING',
    timeOfDay: 'MORNING',
    weather: 'SUNNY',
    commonsQuery: 'Fernsehturm Berlin blossom',
    fallbackImage: 'https://images.unsplash.com/photo-1559564614-a0fb01bba0f9?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 5,
    title: 'Victory Column Snowfield',
    description: 'Expose for the highlights and let the gold statue glow in snowfall.',
    location: 'Siegessaeule',
    lat: 52.5145,
    lng: 13.3501,
    mood: 'MAJESTIC',
    season: 'WINTER',
    timeOfDay: 'MORNING',
    weather: 'SNOWY',
    commonsQuery: 'Siegessaeule Berlin snow',
    fallbackImage: 'https://images.unsplash.com/photo-1485333287248-f62f33f6b490?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 6,
    title: 'Oberbaum Bridge Ember',
    description: 'Capture the U-Bahn silhouette as the sky shifts into blue hour.',
    location: 'Oberbaumbruecke',
    lat: 52.5019,
    lng: 13.4447,
    mood: 'ATMOSPHERIC',
    season: 'ALL',
    timeOfDay: 'EVENING',
    weather: 'CLOUDY',
    commonsQuery: 'Oberbaum Bridge Berlin dusk',
    fallbackImage: 'https://images.unsplash.com/photo-1541752171745-4196eead662a?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 7,
    title: 'East Side Gallery Textures',
    description: 'Focus on one mural and let the wall texture be the subject.',
    location: 'Muehlenstrasse',
    lat: 52.505,
    lng: 13.4397,
    mood: 'URBAN',
    season: 'ALL',
    timeOfDay: 'AFTERNOON',
    weather: 'ANY',
    commonsQuery: 'East Side Gallery Berlin mural',
    fallbackImage: 'https://images.unsplash.com/photo-1520699049698-acd2fccb8cc8?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 8,
    title: 'Tempelhof Minimal Lines',
    description: 'Use negative space and a single runner for scale.',
    location: 'Tempelhofer Feld',
    lat: 52.473,
    lng: 13.4,
    mood: 'MINIMALIST',
    season: 'ALL',
    timeOfDay: 'AFTERNOON',
    weather: 'SUNNY',
    commonsQuery: 'Tempelhofer Feld Berlin',
    fallbackImage: 'https://images.unsplash.com/photo-1563816173747-1510125027e6?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 9,
    title: 'Teufelsberg Echoes',
    description: 'Work the graffiti layers with a wide lens and a moody sky.',
    location: 'Teufelsberg',
    lat: 52.5016,
    lng: 13.2415,
    mood: 'EDGY',
    season: 'ALL',
    timeOfDay: 'ANY',
    weather: 'CLOUDY',
    commonsQuery: 'Teufelsberg Berlin graffiti',
    fallbackImage: 'https://images.unsplash.com/photo-1590425129648-5c4676579e7e?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 10,
    title: 'Museum Island Calm',
    description: 'Long exposures along the river to blur the tourist flow.',
    location: 'Museumsinsel',
    lat: 52.5169,
    lng: 13.4019,
    mood: 'ATMOSPHERIC',
    season: 'ALL',
    timeOfDay: 'MORNING',
    weather: 'CLOUDY',
    commonsQuery: 'Museumsinsel Berlin morning',
    fallbackImage: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 11,
    title: 'Hackesche Hoefe Light',
    description: 'Wait for soft reflections in the art-nouveau tiles.',
    location: 'Hackesche Hoefe',
    lat: 52.5235,
    lng: 13.4029,
    mood: 'ROMANTIC',
    season: 'SPRING',
    timeOfDay: 'AFTERNOON',
    weather: 'SUNNY',
    commonsQuery: 'Hackesche Hoefe Berlin',
    fallbackImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 12,
    title: 'Landwehrkanal Glow',
    description: 'Frame reflections with a low tripod and long shutter.',
    location: 'Landwehrkanal',
    lat: 52.4932,
    lng: 13.4187,
    mood: 'MELANCHOLIC',
    season: 'AUTUMN',
    timeOfDay: 'EVENING',
    weather: 'RAINY',
    commonsQuery: 'Landwehrkanal Berlin evening',
    fallbackImage: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 13,
    title: 'Berlin Cathedral Silhouette',
    description: 'Shoot into the light and emphasize the dome outline.',
    location: 'Berliner Dom',
    lat: 52.5193,
    lng: 13.401,
    mood: 'MAJESTIC',
    season: 'ALL',
    timeOfDay: 'EVENING',
    weather: 'SUNNY',
    commonsQuery: 'Berlin Cathedral sunset',
    fallbackImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 14,
    title: 'Gendarmenmarkt Glow',
    description: 'Layer the twin domes with cafe tables for depth.',
    location: 'Gendarmenmarkt',
    lat: 52.5138,
    lng: 13.3923,
    mood: 'ROMANTIC',
    season: 'WINTER',
    timeOfDay: 'EVENING',
    weather: 'SNOWY',
    commonsQuery: 'Gendarmenmarkt Berlin night',
    fallbackImage: 'https://images.unsplash.com/photo-1519662978599-37b54b833521?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 15,
    title: 'Pfaueninsel Mist',
    description: 'Capture the bridge in soft morning fog for a quiet scene.',
    location: 'Pfaueninsel',
    lat: 52.4445,
    lng: 13.1067,
    mood: 'MELANCHOLIC',
    season: 'AUTUMN',
    timeOfDay: 'MORNING',
    weather: 'FOGGY',
    commonsQuery: 'Pfaueninsel Berlin fog',
    fallbackImage: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 16,
    title: 'Spree River Lines',
    description: 'Use the railing to lead the eye toward the skyline.',
    location: 'Spree Riverwalk',
    lat: 52.5165,
    lng: 13.3779,
    mood: 'MINIMALIST',
    season: 'ALL',
    timeOfDay: 'MORNING',
    weather: 'SUNNY',
    commonsQuery: 'Spree Berlin river',
    fallbackImage: 'https://images.unsplash.com/photo-1504711331083-9c895941bf81?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 17,
    title: 'Kreuzberg Night Neon',
    description: 'Look for a neon sign framed by wet pavement.',
    location: 'Kreuzberg',
    lat: 52.4986,
    lng: 13.4039,
    mood: 'EDGY',
    season: 'ALL',
    timeOfDay: 'NIGHT',
    weather: 'RAINY',
    commonsQuery: 'Kreuzberg Berlin night',
    fallbackImage: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 18,
    title: 'Charlottenburg Garden Symmetry',
    description: 'Use the palace gardens for balanced compositions.',
    location: 'Schloss Charlottenburg',
    lat: 52.5206,
    lng: 13.2953,
    mood: 'MAJESTIC',
    season: 'SPRING',
    timeOfDay: 'AFTERNOON',
    weather: 'SUNNY',
    commonsQuery: 'Charlottenburg Palace garden',
    fallbackImage: 'https://images.unsplash.com/photo-1519606247872-0440aae9b827?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 19,
    title: 'Botanical Glasshouse',
    description: 'Shoot through condensation for abstract layers.',
    location: 'Botanischer Garten',
    lat: 52.4577,
    lng: 13.3067,
    mood: 'ATMOSPHERIC',
    season: 'WINTER',
    timeOfDay: 'AFTERNOON',
    weather: 'RAINY',
    commonsQuery: 'Botanical Garden Berlin greenhouse',
    fallbackImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 20,
    title: 'Volkspark Friedrichshain Trail',
    description: 'Frame a runner through the tall pines for depth.',
    location: 'Volkspark Friedrichshain',
    lat: 52.5286,
    lng: 13.4381,
    mood: 'WARM',
    season: 'SUMMER',
    timeOfDay: 'MORNING',
    weather: 'SUNNY',
    commonsQuery: 'Volkspark Friedrichshain Berlin',
    fallbackImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 21,
    title: 'Berlin Hauptbahnhof Motion',
    description: 'Use slow shutter speeds to paint commuters with light.',
    location: 'Berlin Hauptbahnhof',
    lat: 52.5251,
    lng: 13.3694,
    mood: 'FUTURISTIC',
    season: 'ALL',
    timeOfDay: 'NIGHT',
    weather: 'ANY',
    commonsQuery: 'Berlin Hauptbahnhof night',
    fallbackImage: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 22,
    title: 'Berlin Wall Memorial Quiet',
    description: 'Use leading lines for a contemplative narrative.',
    location: 'Gedenkstaette Berliner Mauer',
    lat: 52.5351,
    lng: 13.3904,
    mood: 'MELANCHOLIC',
    season: 'ALL',
    timeOfDay: 'MORNING',
    weather: 'CLOUDY',
    commonsQuery: 'Berlin Wall Memorial',
    fallbackImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 23,
    title: 'Potsdamer Platz Lines',
    description: 'Look upward and let the modern grid fill the frame.',
    location: 'Potsdamer Platz',
    lat: 52.5096,
    lng: 13.3759,
    mood: 'FUTURISTIC',
    season: 'ALL',
    timeOfDay: 'AFTERNOON',
    weather: 'SUNNY',
    commonsQuery: 'Potsdamer Platz Berlin',
    fallbackImage: 'https://images.unsplash.com/photo-1515444744559-7be63e1600de?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 24,
    title: 'Grunewald Lakeside',
    description: 'Use a telephoto to compress swimmers with the tree line.',
    location: 'Grunewald',
    lat: 52.4722,
    lng: 13.2412,
    mood: 'WARM',
    season: 'SUMMER',
    timeOfDay: 'AFTERNOON',
    weather: 'SUNNY',
    commonsQuery: 'Grunewald Berlin lake',
    fallbackImage: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 25,
    title: 'Prenzlauer Berg Courtyards',
    description: 'Find repeating balconies and a single splash of color.',
    location: 'Prenzlauer Berg',
    lat: 52.5386,
    lng: 13.4247,
    mood: 'URBAN',
    season: 'ALL',
    timeOfDay: 'AFTERNOON',
    weather: 'ANY',
    commonsQuery: 'Prenzlauer Berg Berlin street',
    fallbackImage: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 26,
    title: 'Lietzensee Park Stillness',
    description: 'Mirror the treeline on a calm lake surface.',
    location: 'Lietzenseepark',
    lat: 52.5091,
    lng: 13.3047,
    mood: 'ATMOSPHERIC',
    season: 'SPRING',
    timeOfDay: 'MORNING',
    weather: 'SUNNY',
    commonsQuery: 'Lietzensee Berlin',
    fallbackImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 27,
    title: 'Neue Nationalgalerie Edges',
    description: 'Embrace hard lines and reflections for a minimalist story.',
    location: 'Neue Nationalgalerie',
    lat: 52.5077,
    lng: 13.3673,
    mood: 'MINIMALIST',
    season: 'ALL',
    timeOfDay: 'AFTERNOON',
    weather: 'CLOUDY',
    commonsQuery: 'Neue Nationalgalerie Berlin',
    fallbackImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80'
  },
  {
    id: 28,
    title: 'Tempodrom Light Trails',
    description: 'Position low and catch a bus sweep across the frame.',
    location: 'Tempodrom',
    lat: 52.5034,
    lng: 13.3766,
    mood: 'FUTURISTIC',
    season: 'ALL',
    timeOfDay: 'NIGHT',
    weather: 'ANY',
    commonsQuery: 'Tempodrom Berlin night',
    fallbackImage: 'https://images.unsplash.com/photo-1526401485004-2aa7f3d8b0b5?auto=format&fit=crop&w=1400&q=80'
  }
];
