const INSPIRATIONS = [
    // === STREET PHOTOGRAPHY & URBAN LIFE (18 locations) ===
    {
        id: 1,
        title: "Kreuzberg Graffiti Alley",
        description: "Raw urban art on Wrangelstraße, where street culture meets authentic Berlin vibes.",
        photographyTips: "Use a 35mm or 50mm lens. Shoot in the afternoon when the light hits the walls. Look for interesting contrasts between old and new art.",
        location: "Wrangelstraße, Kreuzberg",
        address: "Wrangelstraße, 10997 Berlin",
        lat: 52.5004,
        lng: 13.4486,
        mood: ["Edgy", "Urban", "Vibrant"],
        season: ["ALL"],
        weatherCondition: ["CLOUDY", "SUNNY", "ANY"],
        timeOfDay: ["AFTERNOON", "MORNING"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1520699049698-acd2fccb8cc8?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin street art graffiti kreuzberg",
        tags: ["street_art", "urban", "graffiti", "kreuzberg"]
    },
    {
        id: 2,
        title: "Turkish Market Reflections",
        description: "The bustling Tuesday and Friday market along Maybachufer canal offers vibrant colors and candid moments.",
        photographyTips: "Arrive early (9-10am) for best light. Use a fast shutter speed (1/250+) for candid portraits. Respect people's privacy.",
        location: "Maybachufer, Neukölln",
        address: "Maybachufer, 12047 Berlin",
        lat: 52.4889,
        lng: 13.4279,
        mood: ["Vibrant", "Energetic", "Warm"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin turkish market neukolln",
        tags: ["market", "street_photography", "candid", "neukolln"]
    },
    {
        id: 3,
        title: "Simon-Dach-Straße Nightlife",
        description: "Friedrichshain's bar street comes alive with neon lights and street life after sunset.",
        photographyTips: "Use wide aperture (f/1.4-f/2.8) and high ISO (1600-3200). Long exposure for light trails. Capture the energy of the crowd.",
        location: "Simon-Dach-Straße, Friedrichshain",
        address: "Simon-Dach-Straße, 10245 Berlin",
        lat: 52.5126,
        lng: 13.4562,
        mood: ["Energetic", "Urban", "Vibrant"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["EVENING", "NIGHT"],
        lightDirection: "ANY",
        difficulty: "ADVANCED",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin nightlife street bars",
        tags: ["nightlife", "street", "friedrichshain", "neon"]
    },
    {
        id: 4,
        title: "Boxhagener Platz Flea Market",
        description: "Sunday flea market with vintage finds, locals, and authentic Berlin atmosphere.",
        photographyTips: "50mm lens for portraits, 24mm for environmental shots. Early morning light is golden. Focus on details and interactions.",
        location: "Boxhagener Platz, Friedrichshain",
        address: "Boxhagener Platz, 10245 Berlin",
        lat: 52.5111,
        lng: 13.4580,
        mood: ["Nostalgic", "Warm", "Urban"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin flea market vintage",
        tags: ["flea_market", "vintage", "sunday", "friedrichshain"]
    },
    {
        id: 5,
        title: "RAW-Gelände Urban Playground",
        description: "Former train depot turned alternative culture hub with street art, clubs, and industrial aesthetics.",
        photographyTips: "Wide angle (16-24mm) for architecture. Look for patterns in textures. Evening light creates dramatic shadows.",
        location: "RAW-Gelände, Friedrichshain",
        address: "Revaler Str. 99, 10245 Berlin",
        lat: 52.5105,
        lng: 13.4551,
        mood: ["Edgy", "Urban", "Atmospheric"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "EVENING", "NIGHT"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin raw gelande industrial",
        tags: ["industrial", "street_art", "urban", "alternative"]
    },
    {
        id: 6,
        title: "Landwehr Canal Paths",
        description: "Tree-lined canal paths perfect for reflections, golden hour portraits, and seasonal changes.",
        photographyTips: "Shoot during golden hour. Use reflections in the water. Long lens (85-135mm) for compressed perspective.",
        location: "Landwehrkanal, Kreuzberg",
        address: "Landwehrkanal, 10999 Berlin",
        lat: 52.4978,
        lng: 13.4129,
        mood: ["Peaceful", "Romantic", "Atmospheric"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "AFTERNOON"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1588788523952-a6fa9c01f2f4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin canal water reflection",
        tags: ["canal", "water", "reflection", "nature"]
    },
    {
        id: 7,
        title: "Helmholtzplatz Café Culture",
        description: "Prenzlauer Berg's beloved square with cafés, street life, and changing seasons.",
        photographyTips: "Capture café culture with 50mm lens. Early morning for empty shots, afternoon for people watching.",
        location: "Helmholtzplatz, Prenzlauer Berg",
        address: "Helmholtzplatz, 10437 Berlin",
        lat: 52.5421,
        lng: 13.4183,
        mood: ["Warm", "Urban", "Peaceful"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin cafe culture prenzlauer berg",
        tags: ["cafe", "street", "prenzlauer_berg", "lifestyle"]
    },
    {
        id: 8,
        title: "Görlitzer Park Street Scenes",
        description: "Diverse urban park capturing Berlin's multicultural essence and street life.",
        photographyTips: "Respectful street photography. 35mm or 50mm lens. Focus on interactions and diverse stories.",
        location: "Görlitzer Park, Kreuzberg",
        address: "Görlitzer Park, 10997 Berlin",
        lat: 52.4952,
        lng: 13.4427,
        mood: ["Urban", "Vibrant", "Diverse"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "EVENING"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1541623089466-8e777dd05d70?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin park people street",
        tags: ["park", "street", "urban", "kreuzberg"]
    },
    {
        id: 9,
        title: "Kastanienallee Vintage Shops",
        description: "Tree-lined street with vintage shops, cafés, and quintessential Berlin character.",
        photographyTips: "Shoot storefronts with character. Window reflections create double exposures. Use natural light.",
        location: "Kastanienallee, Prenzlauer Berg",
        address: "Kastanienallee, 10435 Berlin",
        lat: 52.5325,
        lng: 13.4026,
        mood: ["Nostalgic", "Urban", "Warm"],
        season: ["ALL"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin vintage shop street",
        tags: ["vintage", "shopping", "prenzlauer_berg", "street"]
    },
    {
        id: 10,
        title: "Kottbusser Tor Intersection",
        description: "Gritty urban intersection capturing the raw energy of Berlin's most controversial square.",
        photographyTips: "Use high contrast black & white. Capture movement and urban energy. Stay aware of surroundings.",
        location: "Kottbusser Tor, Kreuzberg",
        address: "Kottbusser Tor, 10999 Berlin",
        lat: 52.4991,
        lng: 13.4183,
        mood: ["Edgy", "Urban", "Dramatic"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "EVENING"],
        lightDirection: "ANY",
        difficulty: "ADVANCED",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin urban street gritty",
        tags: ["urban", "street", "kreuzberg", "gritty"]
    },
    {
        id: 11,
        title: "Markthalle Neun Food Market",
        description: "Historic market hall with food vendors, natural light from skylights, and vibrant atmosphere.",
        photographyTips: "Use available light from skylights. 35mm for context, 85mm for food details. Thursday Street Food market is busiest.",
        location: "Markthalle Neun, Kreuzberg",
        address: "Eisenbahnstraße 42, 10997 Berlin",
        lat: 52.4986,
        lng: 13.4300,
        mood: ["Vibrant", "Warm", "Energetic"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "EVENING"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1567521463850-4048e42c6dea?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin food market hall",
        tags: ["food", "market", "indoor", "kreuzberg"]
    },
    {
        id: 12,
        title: "U-Bahn Platform Light Trails",
        description: "Capture the iconic yellow U-Bahn trains with light trails at various atmospheric stations.",
        photographyTips: "Use 1-2 second exposure for light trails. Eberswalder Straße or Schlesisches Tor stations are photogenic. Use tripod or stabilize.",
        location: "Various U-Bahn Stations",
        address: "U-Bahn Schlesisches Tor, 10997 Berlin",
        lat: 52.4999,
        lng: 13.4423,
        mood: ["Urban", "Atmospheric", "Futuristic"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["EVENING", "NIGHT"],
        lightDirection: "ANY",
        difficulty: "ADVANCED",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1520699049698-acd2fccb8cc8?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin ubahn metro train",
        tags: ["ubahn", "metro", "transport", "night"]
    },
    {
        id: 13,
        title: "Bergmannstraße Street Life",
        description: "Charming pedestrian street with independent shops, cafés, and Saturday farmer's market.",
        photographyTips: "Capture street portraits and shop details. Saturday morning market offers best action. Use natural light.",
        location: "Bergmannstraße, Kreuzberg",
        address: "Bergmannstraße, 10961 Berlin",
        lat: 52.4911,
        lng: 13.3933,
        mood: ["Warm", "Urban", "Peaceful"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin street market kreuzberg",
        tags: ["street", "market", "kreuzberg", "shopping"]
    },
    {
        id: 14,
        title: "Admiralbrücke Golden Hour",
        description: "Iconic bridge over Landwehr Canal where locals gather for sunset beers and music.",
        photographyTips: "Arrive before sunset. Capture silhouettes against golden sky. Wide angle for scene, telephoto for portraits.",
        location: "Admiralbrücke, Kreuzberg",
        address: "Admiralbrücke, 10999 Berlin",
        lat: 52.5004,
        lng: 13.4129,
        mood: ["Atmospheric", "Warm", "Urban"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin bridge sunset people",
        tags: ["bridge", "sunset", "social", "kreuzberg"]
    },
    {
        id: 15,
        title: "Warschauer Straße Railway Arches",
        description: "Industrial railway arches with street art, bars, and urban atmosphere beneath tracks.",
        photographyTips: "Black & white works well. Capture patterns in architecture. Evening when lights come on for ambiance.",
        location: "Warschauer Straße, Friedrichshain",
        address: "Warschauer Straße, 10245 Berlin",
        lat: 52.5063,
        lng: 13.4492,
        mood: ["Urban", "Edgy", "Atmospheric"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "EVENING"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin railway arches industrial",
        tags: ["industrial", "arches", "urban", "friedrichshain"]
    },
    {
        id: 16,
        title: "Mehringdamm Market Bustle",
        description: "Local weekly market with authentic Berlin produce, flowers, and street vendors.",
        photographyTips: "Capture vendor interactions and colorful produce. Morning light is best. 50mm for intimate shots.",
        location: "Mehringdamm, Kreuzberg",
        address: "Mehringdamm, 10961 Berlin",
        lat: 52.4945,
        lng: 13.3882,
        mood: ["Vibrant", "Energetic", "Warm"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin market vendors produce",
        tags: ["market", "street", "vendors", "kreuzberg"]
    },
    {
        id: 17,
        title: "Oranienstraße Nighttime",
        description: "Kreuzberg's main artery with bars, kebab shops, and diverse nightlife energy.",
        photographyTips: "High ISO (1600-3200), wide aperture. Capture neon signs and street life. Be respectful and aware.",
        location: "Oranienstraße, Kreuzberg",
        address: "Oranienstraße, 10999 Berlin",
        lat: 52.5001,
        lng: 13.4237,
        mood: ["Energetic", "Urban", "Diverse"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["EVENING", "NIGHT"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin street night lights",
        tags: ["nightlife", "street", "kreuzberg", "diverse"]
    },
    {
        id: 18,
        title: "Paul-Lincke-Ufer Canal Side",
        description: "Picturesque canal-side street with cafés, autumn trees, and quintessential Berlin atmosphere.",
        photographyTips: "Autumn colors are spectacular. Shoot from bridges for elevated views. Golden hour for warm tones.",
        location: "Paul-Lincke-Ufer, Kreuzberg",
        address: "Paul-Lincke-Ufer, 10999 Berlin",
        lat: 52.5003,
        lng: 13.4179,
        mood: ["Peaceful", "Romantic", "Warm"],
        season: ["AUTUMN", "SPRING", "SUMMER"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "AFTERNOON"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1588788523952-a6fa9c01f2f4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin canal trees autumn",
        tags: ["canal", "autumn", "trees", "kreuzberg"]
    },

    // === ICONIC LANDMARKS (12 locations) ===
    {
        id: 19,
        title: "Brandenburg Gate Rain Reflections",
        description: "The iconic gate reflected in puddles on Pariser Platz during rainy weather.",
        photographyTips: "Get low to capture reflections. Use wide angle. Blue hour or night for dramatic lighting.",
        location: "Pariser Platz, Mitte",
        address: "Pariser Platz, 10117 Berlin",
        lat: 52.5163,
        lng: 13.3777,
        mood: ["Majestic", "Dramatic", "Melancholic"],
        season: ["ALL"],
        weatherCondition: ["RAINY", "CLOUDY"],
        timeOfDay: ["EVENING", "BLUE_HOUR"],
        lightDirection: "WEST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1599424423953-27203673474e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "brandenburg gate berlin rain",
        tags: ["landmark", "iconic", "rain", "reflection"]
    },
    {
        id: 20,
        title: "Reichstag Dome Spiral",
        description: "The glass dome's interior spiral staircase and architecture by Norman Foster.",
        photographyTips: "Book in advance (free). Wide angle lens essential. Morning light through glass is beautiful.",
        location: "Platz der Republik, Mitte",
        address: "Platz der Republik 1, 11011 Berlin",
        lat: 52.5186,
        lng: 13.3761,
        mood: ["Futuristic", "Majestic", "Architectural"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "FREE",
        imageUrl: "https://images.unsplash.com/photo-1568528806662-e5a43e8c19b2?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "reichstag dome berlin interior",
        tags: ["architecture", "modern", "landmark", "indoor"]
    },
    {
        id: 21,
        title: "TV Tower Through Cherry Blossoms",
        description: "Frame the Fernsehturm through blooming cherry trees in spring.",
        photographyTips: "Use shallow depth of field to blur blossoms in foreground. Best in late April. Morning or evening light.",
        location: "Near Mauerpark, Prenzlauer Berg",
        address: "Mauerpark, 10437 Berlin",
        lat: 52.5426,
        lng: 13.4028,
        mood: ["Romantic", "Vibrant", "Peaceful"],
        season: ["SPRING"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "GOLDEN_HOUR"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1559564614-a0fb01bba0f9?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin tv tower cherry blossoms",
        tags: ["landmark", "spring", "cherry_blossoms", "tv_tower"]
    },
    {
        id: 22,
        title: "Holocaust Memorial Waves",
        description: "The undulating concrete stelae create powerful geometric patterns and shadows.",
        photographyTips: "Wide angle from ground level or elevated view. Late afternoon sun creates dramatic shadows. Respectful approach essential.",
        location: "Cora-Berliner-Straße, Mitte",
        address: "Cora-Berliner-Straße 1, 10117 Berlin",
        lat: 52.5139,
        lng: 13.3788,
        mood: ["Somber", "Powerful", "Minimalist"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1571981521188-0c30e3d8f3d0?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "holocaust memorial berlin",
        tags: ["memorial", "architecture", "landmark", "respectful"]
    },
    {
        id: 23,
        title: "Checkpoint Charlie Perspective",
        description: "Historic Cold War crossing point with the iconic guardhouse and signage.",
        photographyTips: "Arrive early to avoid crowds. Use tilt-shift or perspective correction. Include surrounding modern buildings for contrast.",
        location: "Friedrichstraße, Kreuzberg",
        address: "Friedrichstraße 43-45, 10969 Berlin",
        lat: 52.5075,
        lng: 13.3903,
        mood: ["Historic", "Urban", "Nostalgic"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "checkpoint charlie berlin",
        tags: ["historic", "landmark", "cold_war", "iconic"]
    },
    {
        id: 24,
        title: "Victory Column Golden Statue",
        description: "The golden Siegessäule shining against blue or dramatic skies.",
        photographyTips: "Climb for panoramic views (small fee). Shoot from Tiergarten for foreground. Best in morning light.",
        location: "Großer Stern, Tiergarten",
        address: "Großer Stern 1, 10557 Berlin",
        lat: 52.5145,
        lng: 13.3501,
        mood: ["Majestic", "Powerful", "Golden"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1485333287248-f62f33f6b490?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "siegessaule victory column berlin",
        tags: ["landmark", "monument", "golden", "tiergarten"]
    },
    {
        id: 25,
        title: "Berlin Cathedral Dome Details",
        description: "The impressive Berliner Dom with its copper dome and baroque architecture.",
        photographyTips: "Shoot from Museum Island or across the Spree. Climb dome for city views (fee). Evening illumination is spectacular.",
        location: "Lustgarten, Museum Island",
        address: "Am Lustgarten, 10178 Berlin",
        lat: 52.5191,
        lng: 13.4009,
        mood: ["Majestic", "Historic", "Ornate"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON", "BLUE_HOUR"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1590425129648-5c4676579e7e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin cathedral dom",
        tags: ["cathedral", "landmark", "architecture", "historic"]
    },
    {
        id: 26,
        title: "East Side Gallery Colors",
        description: "The longest remaining Berlin Wall section covered in iconic murals and street art.",
        photographyTips: "Focus on specific murals rather than wide shots. Early morning for empty frames. Detail shots of texture and aging paint.",
        location: "Mühlenstraße, Friedrichshain",
        address: "Mühlenstraße, 10243 Berlin",
        lat: 52.5050,
        lng: 13.4397,
        mood: ["Historic", "Vibrant", "Powerful"],
        season: ["ALL"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1520699049698-acd2fccb8cc8?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "east side gallery berlin wall",
        tags: ["street_art", "historic", "wall", "landmark"]
    },
    {
        id: 27,
        title: "Gendarmenmarkt Square Symphony",
        description: "Berlin's most beautiful square framed by twin cathedrals and Konzerthaus.",
        photographyTips: "Center composition between the three buildings. Christmas market in winter is magical. Blue hour lighting is best.",
        location: "Gendarmenmarkt, Mitte",
        address: "Gendarmenmarkt, 10117 Berlin",
        lat: 52.5134,
        lng: 13.3921,
        mood: ["Majestic", "Elegant", "Historic"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["BLUE_HOUR", "EVENING"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1599951753380-d8c0cc86f029?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "gendarmenmarkt berlin",
        tags: ["landmark", "square", "architecture", "historic"]
    },
    {
        id: 28,
        title: "Kaiser Wilhelm Memorial Church Ruins",
        description: "The damaged church tower preserved as war memorial next to modern chapel.",
        photographyTips: "Contrast old and new architecture. Blue glass of modern church glows at dusk. Wide angle for juxtaposition.",
        location: "Breitscheidplatz, Charlottenburg",
        address: "Breitscheidplatz, 10789 Berlin",
        lat: 52.5050,
        lng: 13.3358,
        mood: ["Historic", "Somber", "Powerful"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "BLUE_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1590425129648-5c4676579e7e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "kaiser wilhelm church berlin",
        tags: ["historic", "memorial", "church", "architecture"]
    },
    {
        id: 29,
        title: "Charlottenburg Palace Gardens",
        description: "Baroque palace with formal gardens, fountains, and romantic atmosphere.",
        photographyTips: "Spring flowers or autumn colors. Wide angle for palace facade. Garden details with telephoto.",
        location: "Spandauer Damm, Charlottenburg",
        address: "Spandauer Damm 10-22, 14059 Berlin",
        lat: 52.5208,
        lng: 13.2957,
        mood: ["Romantic", "Elegant", "Historic"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "charlottenburg palace berlin gardens",
        tags: ["palace", "gardens", "historic", "romantic"]
    },
    {
        id: 30,
        title: "Alexanderplatz Cyberpunk",
        description: "Urban plaza with TV Tower, trams, and neon signs creating futuristic atmosphere.",
        photographyTips: "Long exposure at night for light trails. Rain adds cyberpunk feel. Use high vantage points.",
        location: "Alexanderplatz, Mitte",
        address: "Alexanderplatz, 10178 Berlin",
        lat: 52.5219,
        lng: 13.4132,
        mood: ["Futuristic", "Urban", "Energetic"],
        season: ["ALL"],
        weatherCondition: ["ANY", "RAINY"],
        timeOfDay: ["EVENING", "NIGHT"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1560930950-5cc20e80e392?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "alexanderplatz berlin night",
        tags: ["urban", "night", "futuristic", "landmark"]
    },

    // === BRIDGES & WATERWAYS (10 locations) ===
    {
        id: 31,
        title: "Oberbaum Bridge Sunset",
        description: "The iconic double-deck bridge with U-Bahn crossing at golden hour.",
        photographyTips: "Shoot from Spree riverside. Time your shot with U-Bahn crossing. Best sunset spot in Berlin.",
        location: "Oberbaumbrücke, Friedrichshain-Kreuzberg",
        address: "Oberbaumbrücke, 10243 Berlin",
        lat: 52.5019,
        lng: 13.4447,
        mood: ["Atmospheric", "Romantic", "Majestic"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1541752171745-4196eead662a?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "oberbaum bridge berlin sunset",
        tags: ["bridge", "sunset", "ubahn", "iconic"]
    },
    {
        id: 32,
        title: "Molecule Man Sunrise",
        description: "30-meter aluminum sculpture where three boroughs meet, perfect for blue hour reflections.",
        photographyTips: "Shoot from Oberbaum Bridge or riverside. Long exposure for mirror effect. Best at sunrise or blue hour.",
        location: "Spree River, Treptow",
        address: "Spree, 10243 Berlin",
        lat: 52.4988,
        lng: 13.4517,
        mood: ["Minimalist", "Atmospheric", "Modern"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY", "FOGGY"],
        timeOfDay: ["SUNRISE", "BLUE_HOUR"],
        lightDirection: "EAST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1599951753380-d8c0cc86f029?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "molecule man berlin sculpture",
        tags: ["sculpture", "water", "sunrise", "modern_art"]
    },
    {
        id: 33,
        title: "Monbijou Bridge View",
        description: "Small pedestrian bridge offering perfect views of Museum Island and Berlin Cathedral.",
        photographyTips: "Golden hour for warm light on cathedral dome. Include bridge railings for foreground interest.",
        location: "Monbijoubrücke, Mitte",
        address: "Monbijoubrücke, 10178 Berlin",
        lat: 52.5210,
        lng: 13.3978,
        mood: ["Romantic", "Historic", "Peaceful"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "AFTERNOON"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1588788523952-a6fa9c01f2f4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin bridge museum island",
        tags: ["bridge", "view", "museum_island", "cathedral"]
    },
    {
        id: 34,
        title: "Spree River Boat Trails",
        description: "Capture tour boats creating light trails on the Spree at dusk.",
        photographyTips: "Long exposure (10-30 seconds) from stable position. Best spots near Reichstag or Museum Island.",
        location: "Spree River, various locations",
        address: "Spree River, 10117 Berlin",
        lat: 52.5186,
        lng: 13.3761,
        mood: ["Atmospheric", "Peaceful", "Urban"],
        season: ["ALL"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["BLUE_HOUR", "EVENING"],
        lightDirection: "ANY",
        difficulty: "ADVANCED",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1541623089466-8e777dd05d70?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin spree river boats evening",
        tags: ["river", "boats", "long_exposure", "evening"]
    },
    {
        id: 35,
        title: "Schleusenkrug Beer Garden Canal",
        description: "Historic beer garden by the canal lock with weeping willows and boat traffic.",
        photographyTips: "Summer afternoons capture the relaxed atmosphere. Include canal boats and willow trees.",
        location: "Tiergarten, near Zoo",
        address: "Müller-Breslau-Straße, 10623 Berlin",
        lat: 52.5079,
        lng: 13.3379,
        mood: ["Peaceful", "Warm", "Relaxed"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin beer garden canal",
        tags: ["beer_garden", "canal", "summer", "relaxed"]
    },
    {
        id: 36,
        title: "Jungfernbrücke Historic Bridge",
        description: "Berlin's oldest bridge, a charming drawbridge from 1798 over small canal.",
        photographyTips: "Detail shots of historic mechanism. Evening light for warm tones. Less crowded than major spots.",
        location: "Friedrichsgracht, Mitte",
        address: "Friedrichsgracht, 10178 Berlin",
        lat: 52.5156,
        lng: 13.4059,
        mood: ["Historic", "Nostalgic", "Charming"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1588788523952-a6fa9c01f2f4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin historic bridge canal",
        tags: ["bridge", "historic", "canal", "charming"]
    },
    {
        id: 37,
        title: "Urban Spree Riverside Culture",
        description: "Alternative art space along the Spree with outdoor installations and river views.",
        photographyTips: "Combine street art with river background. Sunset colors reflect on water. Check for events.",
        location: "Revaler Straße, Friedrichshain",
        address: "Revaler Str. 99, 10245 Berlin",
        lat: 52.5092,
        lng: 13.4540,
        mood: ["Urban", "Artistic", "Alternative"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin spree riverside art",
        tags: ["river", "art", "alternative", "urban"]
    },
    {
        id: 38,
        title: "Rummelsburg Bay Sunset",
        description: "Quiet bay area with sailing boats, industrial backdrop, and spectacular sunsets.",
        photographyTips: "Long lens to compress perspective. Silhouettes of boats against colorful sky. Less touristy spot.",
        location: "Rummelsburger Bucht, Lichtenberg",
        address: "Rummelsburger Bucht, 10317 Berlin",
        lat: 52.4992,
        lng: 13.4879,
        mood: ["Peaceful", "Atmospheric", "Nostalgic"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin bay boats sunset",
        tags: ["bay", "boats", "sunset", "peaceful"]
    },
    {
        id: 39,
        title: "Plänterwald Spree Forest Feel",
        description: "Less known forest area along the Spree with mysterious, fairy-tale atmosphere.",
        photographyTips: "Misty mornings create magical mood. Use trees as frames. Explore abandoned Spreepark nearby.",
        location: "Plänterwald, Treptow",
        address: "Plänterwald, 12437 Berlin",
        lat: 52.4781,
        lng: 13.4813,
        mood: ["Mysterious", "Peaceful", "Atmospheric"],
        season: ["AUTUMN", "WINTER", "SPRING"],
        weatherCondition: ["FOGGY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin forest spree mysterious",
        tags: ["forest", "river", "mysterious", "nature"]
    },
    {
        id: 40,
        title: "Treptower Hafen Marina",
        description: "Small harbor with houseboats, reflections, and relaxed waterfront atmosphere.",
        photographyTips: "Morning for calm water reflections. Capture houseboat details. Use long exposure for smooth water.",
        location: "Treptower Hafen, Treptow",
        address: "An der Lohmühleninsel, 12435 Berlin",
        lat: 52.4917,
        lng: 13.4789,
        mood: ["Peaceful", "Nostalgic", "Relaxed"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "GOLDEN_HOUR"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1563407893019-37ed3eed13a4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin marina boats harbor",
        tags: ["marina", "boats", "water", "peaceful"]
    },

    // === PARKS & NATURE (12 locations) ===
    {
        id: 41,
        title: "Tiergarten Autumn Tunnel",
        description: "Tree-lined paths create natural tunnels with spectacular autumn colors.",
        photographyTips: "Use leading lines. Shoot during leaf fall for golden atmosphere. Morning mist adds magic.",
        location: "Tiergarten Park, Mitte",
        address: "Straße des 17. Juni, 10785 Berlin",
        lat: 52.5145,
        lng: 13.3501,
        mood: ["Peaceful", "Romantic", "Warm"],
        season: ["AUTUMN", "SPRING"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin tiergarten autumn trees",
        tags: ["park", "autumn", "trees", "nature"]
    },
    {
        id: 42,
        title: "Tempelhofer Feld Minimalism",
        description: "Vast former airport runway perfect for minimalist compositions and big skies.",
        photographyTips: "Use negative space. Single subjects work well. Windy days for kites. Long shadows at golden hour.",
        location: "Tempelhofer Feld, Tempelhof",
        address: "Tempelhofer Damm, 12101 Berlin",
        lat: 52.4730,
        lng: 13.4000,
        mood: ["Minimalist", "Spacious", "Free"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1563816173747-1510125027e6?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "tempelhof field berlin minimalist",
        tags: ["park", "minimalist", "sky", "open_space"]
    },
    {
        id: 43,
        title: "Viktoriapark Waterfall",
        description: "Berlin's only waterfall cascading down Kreuzberg hill with monument on top.",
        photographyTips: "Long exposure (1-4 seconds) for silky water. Best after rain. Climb monument for city views.",
        location: "Viktoriapark, Kreuzberg",
        address: "Kreuzbergstraße, 10965 Berlin",
        lat: 52.4892,
        lng: 13.3820,
        mood: ["Peaceful", "Natural", "Romantic"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["CLOUDY", "RAINY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1502691876148-a84978e59af8?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "waterfall forest green",
        tags: ["waterfall", "nature", "park", "kreuzberg"]
    },
    {
        id: 44,
        title: "Grunewald Forest Paths",
        description: "Dense forest with winding paths, perfect for nature photography and moody atmospheres.",
        photographyTips: "Overcast days for even forest light. Include paths for depth. Autumn colors are spectacular.",
        location: "Grunewald Forest, Charlottenburg-Wilmersdorf",
        address: "Grunewald, 14193 Berlin",
        lat: 52.4736,
        lng: 13.2603,
        mood: ["Peaceful", "Mysterious", "Natural"],
        season: ["AUTUMN", "SPRING", "SUMMER"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin forest path trees",
        tags: ["forest", "nature", "trees", "hiking"]
    },
    {
        id: 45,
        title: "Treptower Park Soviet Memorial",
        description: "Imposing Soviet war memorial surrounded by park, perfect for dramatic compositions.",
        photographyTips: "Wide angle for monument scale. Symmetry works well. Evening light for dramatic mood.",
        location: "Treptower Park, Treptow",
        address: "Puschkinallee, 12435 Berlin",
        lat: 52.4883,
        lng: 13.4686,
        mood: ["Powerful", "Historic", "Dramatic"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1590425129648-5c4676579e7e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin soviet memorial monument",
        tags: ["memorial", "historic", "park", "monument"]
    },
    {
        id: 46,
        title: "Volkspark Friedrichshain Fountain",
        description: "Berlin's oldest public park with fairy tale fountain and varied landscapes.",
        photographyTips: "Fountain best in summer. Multiple ponds for reflections. Cherry blossoms in spring.",
        location: "Volkspark Friedrichshain",
        address: "Am Friedrichshain, 10249 Berlin",
        lat: 52.5257,
        lng: 13.4317,
        mood: ["Peaceful", "Romantic", "Green"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin park fountain",
        tags: ["park", "fountain", "nature", "friedrichshain"]
    },
    {
        id: 47,
        title: "Mauerpark Amphitheater",
        description: "Former death strip turned vibrant park with Sunday karaoke and flea market.",
        photographyTips: "Sunday afternoons capture the energy. Wide angle for crowd scenes. Graffiti walls for color.",
        location: "Mauerpark, Prenzlauer Berg",
        address: "Gleimstraße 55, 10437 Berlin",
        lat: 52.5426,
        lng: 13.4028,
        mood: ["Energetic", "Vibrant", "Social"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1506810487138-47e46fae7a1b?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin mauerpark people",
        tags: ["park", "social", "flea_market", "vibrant"]
    },
    {
        id: 48,
        title: "Körnerpark Hidden Gem",
        description: "Small baroque-style park with rose garden, fountain, and gallery - a hidden oasis.",
        photographyTips: "Perfect for afternoon tea. Formal gardens offer symmetry. Best in rose blooming season (June).",
        location: "Körnerpark, Neukölln",
        address: "Schierker Straße 8, 12051 Berlin",
        lat: 52.4783,
        lng: 13.4517,
        mood: ["Romantic", "Peaceful", "Elegant"],
        season: ["SPRING", "SUMMER"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin garden roses baroque",
        tags: ["garden", "roses", "hidden_gem", "romantic"]
    },
    {
        id: 49,
        title: "Botanical Garden Glasshouses",
        description: "One of the world's largest botanical gardens with stunning Victorian glasshouses.",
        photographyTips: "Tropical houses offer exotic subjects. Late afternoon light through glass is beautiful. Macro lens for flower details.",
        location: "Botanical Garden, Steglitz",
        address: "Königin-Luise-Straße 6-8, 14195 Berlin",
        lat: 52.4580,
        lng: 13.3063,
        mood: ["Peaceful", "Exotic", "Natural"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "botanical garden glasshouse tropical",
        tags: ["garden", "tropical", "plants", "indoor"]
    },
    {
        id: 50,
        title: "Lietzensee Lake Reflections",
        description: "Peaceful lake in Charlottenburg perfect for reflection photography and waterfowl.",
        photographyTips: "Morning for glass-like water. Include surrounding trees. Sunset colors reflect beautifully.",
        location: "Lietzensee, Charlottenburg",
        address: "Witzlebenstraße, 14057 Berlin",
        lat: 52.5101,
        lng: 13.2931,
        mood: ["Peaceful", "Serene", "Natural"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "GOLDEN_HOUR"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "lake reflection peaceful",
        tags: ["lake", "reflection", "nature", "peaceful"]
    },
    {
        id: 51,
        title: "Britzer Garten Tulip Fields",
        description: "Large landscape park famous for spring tulip displays with thousands of flowers.",
        photographyTips: "Mid-April to early May for tulips. Wide angle for fields, macro for details. Colorful and vibrant.",
        location: "Britzer Garten, Neukölln",
        address: "Sangerhauser Weg 1, 12349 Berlin",
        lat: 52.4344,
        lng: 13.4086,
        mood: ["Vibrant", "Cheerful", "Colorful"],
        season: ["SPRING"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "tulip field colorful spring",
        tags: ["flowers", "tulips", "spring", "colorful"]
    },
    {
        id: 52,
        title: "Gleisdreieck Park Urban Green",
        description: "Modern park built on old railway grounds, mixing industrial heritage with nature.",
        photographyTips: "Old railway elements provide interesting foregrounds. Modern park design works for minimalism.",
        location: "Park am Gleisdreieck, Kreuzberg",
        address: "Möckernstraße 26, 10963 Berlin",
        lat: 52.4969,
        lng: 13.3771,
        mood: ["Urban", "Modern", "Peaceful"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin park urban green",
        tags: ["park", "urban", "modern", "industrial"]
    },

    // === ARCHITECTURE (10 locations) ===
    {
        id: 53,
        title: "Bauhaus Archive Curves",
        description: "Walter Gropius's iconic building with distinctive curved roof and modernist design.",
        photographyTips: "Strong geometric shapes. Best in side lighting. White building pops against blue sky.",
        location: "Bauhaus Archive, Tiergarten",
        address: "Klingelhöferstraße 14, 10785 Berlin",
        lat: 52.5065,
        lng: 13.3586,
        mood: ["Modern", "Minimalist", "Architectural"],
        season: ["ALL"],
        weatherCondition: ["SUNNY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "SOUTH",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "bauhaus architecture berlin",
        tags: ["architecture", "bauhaus", "modern", "design"]
    },
    {
        id: 54,
        title: "Potsdamer Platz Glass Towers",
        description: "Modern glass skyscrapers creating reflections and geometric patterns.",
        photographyTips: "Look up for leading lines. Use reflections in glass. Blue hour for illuminated buildings.",
        location: "Potsdamer Platz, Mitte",
        address: "Potsdamer Platz, 10785 Berlin",
        lat: 52.5096,
        lng: 13.3756,
        mood: ["Futuristic", "Urban", "Modern"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "BLUE_HOUR"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin modern architecture glass",
        tags: ["architecture", "modern", "glass", "skyscraper"]
    },
    {
        id: 55,
        title: "Corbusier Haus Brutalism",
        description: "Iconic brutalist residential tower by Le Corbusier, bold concrete architecture.",
        photographyTips: "Emphasize brutal concrete textures. Colorful balconies provide contrast. Geometric compositions.",
        location: "Corbusierhaus, Westend",
        address: "Flatowallee 16, 14055 Berlin",
        lat: 52.5139,
        lng: 13.2708,
        mood: ["Dramatic", "Bold", "Architectural"],
        season: ["ALL"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["AFTERNOON"],
        lightDirection: "SOUTH",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1495510096868-e0c3455df0b6?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "brutalist architecture concrete",
        tags: ["architecture", "brutalist", "concrete", "bold"]
    },
    {
        id: 56,
        title: "Hufeisensiedlung Horseshoe",
        description: "UNESCO World Heritage housing estate with distinctive horseshoe shape and colorful facades.",
        photographyTips: "Aerial view for horseshoe shape (drone). Detail shots of colorful doors and windows.",
        location: "Hufeisensiedlung, Britz",
        address: "Fritz-Reuter-Allee, 12359 Berlin",
        lat: 52.4481,
        lng: 13.4458,
        mood: ["Colorful", "Architectural", "Historic"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "colorful housing berlin",
        tags: ["architecture", "colorful", "housing", "unesco"]
    },
    {
        id: 57,
        title: "Futurium Science Museum",
        description: "Ultra-modern museum of the future with striking geometric architecture.",
        photographyTips: "Wide angle for dramatic angles. White architecture glows at dusk. Reflections in Spree.",
        location: "Alexanderufer, Mitte",
        address: "Alexanderufer 2, 10117 Berlin",
        lat: 52.5248,
        lng: 13.3776,
        mood: ["Futuristic", "Modern", "Clean"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["AFTERNOON", "BLUE_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "modern architecture white geometric",
        tags: ["architecture", "modern", "futuristic", "museum"]
    },
    {
        id: 58,
        title: "Hackesche Höfe Courtyards",
        description: "Art Nouveau courtyard complex with colorful tiles and cultural venues.",
        photographyTips: "Capture the ornate tile work. Multiple courtyards offer variety. Evening when cafés are lit.",
        location: "Hackesche Höfe, Mitte",
        address: "Rosenthaler Straße 40, 10178 Berlin",
        lat: 52.5251,
        lng: 13.4018,
        mood: ["Historic", "Colorful", "Charming"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "EVENING"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin courtyard tiles colorful",
        tags: ["architecture", "art_nouveau", "courtyard", "historic"]
    },
    {
        id: 59,
        title: "Zionskirche Church Square",
        description: "Historic church in Prenzlauer Berg with beautiful square and autumn trees.",
        photographyTips: "Autumn colors frame the church beautifully. Golden hour side-lighting on brick facade.",
        location: "Zionskirchplatz, Prenzlauer Berg",
        address: "Zionskirchplatz, 10119 Berlin",
        lat: 52.5333,
        lng: 13.4010,
        mood: ["Historic", "Peaceful", "Romantic"],
        season: ["AUTUMN", "SPRING"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "AFTERNOON"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin church autumn trees",
        tags: ["church", "historic", "autumn", "architecture"]
    },
    {
        id: 60,
        title: "Jewish Museum Libeskind",
        description: "Deconstructivist architecture by Daniel Libeskind with powerful angular design.",
        photographyTips: "Strong angles and lines. Zinc facade changes in different weather. Respectful approach essential.",
        location: "Jewish Museum, Kreuzberg",
        address: "Lindenstraße 9-14, 10969 Berlin",
        lat: 52.5022,
        lng: 13.3950,
        mood: ["Powerful", "Dramatic", "Somber"],
        season: ["ALL"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["AFTERNOON"],
        lightDirection: "SOUTH",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "jewish museum berlin architecture",
        tags: ["museum", "architecture", "modern", "memorial"]
    },
    {
        id: 61,
        title: "Neue Nationalgalerie Mies van der Rohe",
        description: "Modernist glass and steel pavilion by Mies van der Rohe, icon of minimalism.",
        photographyTips: "Clean lines and reflections. Best in dramatic weather. Black steel against sky.",
        location: "Kulturforum, Tiergarten",
        address: "Potsdamer Straße 50, 10785 Berlin",
        lat: 52.5088,
        lng: 13.3673,
        mood: ["Minimalist", "Elegant", "Modern"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "BLUE_HOUR"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "mies van der rohe glass pavilion",
        tags: ["architecture", "modernist", "glass", "minimalist"]
    },
    {
        id: 62,
        title: "Arena Berlin Industrial",
        description: "Converted factory complex with industrial architecture and Spree views.",
        photographyTips: "Industrial textures and patterns. Sunset over Spree in background. Check for events.",
        location: "Arena Berlin, Treptow",
        address: "Eichenstraße 4, 12435 Berlin",
        lat: 52.4935,
        lng: 13.4525,
        mood: ["Industrial", "Urban", "Edgy"],
        season: ["ALL"],
        weatherCondition: ["ANY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin industrial architecture",
        tags: ["industrial", "architecture", "urban", "converted"]
    },

    // === SEASONAL SPOTS (8 locations) ===
    {
        id: 63,
        title: "Bolle Park Cherry Blossoms",
        description: "One of Berlin's best cherry blossom spots with rows of blooming trees.",
        photographyTips: "Peak bloom late April. Arrive early to avoid crowds. Use shallow depth of field for dreamy effect.",
        location: "Schillerpark Kiez, Wedding",
        address: "Schwedenstraße, 13359 Berlin",
        lat: 52.5574,
        lng: 13.3619,
        mood: ["Romantic", "Dreamy", "Vibrant"],
        season: ["SPRING"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["MORNING", "GOLDEN_HOUR"],
        lightDirection: "EAST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "cherry blossoms pink spring",
        tags: ["cherry_blossoms", "spring", "flowers", "romantic"]
    },
    {
        id: 64,
        title: "Gendarmenmarkt Christmas Market",
        description: "Berlin's most elegant Christmas market with illuminated cathedrals.",
        photographyTips: "Blue hour for best atmosphere. Long exposure for crowd blur. Capture warm lights and architecture.",
        location: "Gendarmenmarkt, Mitte",
        address: "Gendarmenmarkt, 10117 Berlin",
        lat: 52.5134,
        lng: 13.3921,
        mood: ["Festive", "Romantic", "Warm"],
        season: ["WINTER"],
        weatherCondition: ["ANY", "SNOWY"],
        timeOfDay: ["BLUE_HOUR", "EVENING"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1544988238-1bdec4e4b581?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "christmas market berlin lights",
        tags: ["christmas", "winter", "market", "festive"]
    },
    {
        id: 65,
        title: "Stralau Beach Summer Vibes",
        description: "Small urban beach with sunset views over the Spree, perfect for summer golden hour.",
        photographyTips: "Capture beach bar atmosphere. Sunset silhouettes. Use people for scale and life.",
        location: "Stralauer Beach, Friedrichshain",
        address: "An der Schillingbrücke, 10243 Berlin",
        lat: 52.5053,
        lng: 13.4347,
        mood: ["Relaxed", "Warm", "Social"],
        season: ["SUMMER"],
        weatherCondition: ["SUNNY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "urban beach sunset summer",
        tags: ["summer", "beach", "sunset", "social"]
    },
    {
        id: 66,
        title: "Tiergarten Snow Silence",
        description: "Winter transforms the park into a peaceful snow-covered wonderland.",
        photographyTips: "Fresh snow in morning light. Overexpose slightly (+1 EV) to keep snow white. Minimal compositions work well.",
        location: "Tiergarten Park, Mitte",
        address: "Straße des 17. Juni, 10785 Berlin",
        lat: 52.5145,
        lng: 13.3501,
        mood: ["Peaceful", "Minimalist", "Serene"],
        season: ["WINTER"],
        weatherCondition: ["SNOWY"],
        timeOfDay: ["MORNING", "AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1478827536114-da961b7f86cf?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "snow park winter peaceful",
        tags: ["winter", "snow", "park", "peaceful"]
    },
    {
        id: 67,
        title: "Kreuzberg Autumn Street Trees",
        description: "Residential streets in Kreuzberg explode with golden autumn colors.",
        photographyTips: "Mid to late October for peak colors. Overcast days for saturated colors. Include architecture.",
        location: "Various streets, Kreuzberg",
        address: "Mehringdamm area, 10961 Berlin",
        lat: 52.4945,
        lng: 13.3882,
        mood: ["Warm", "Nostalgic", "Cozy"],
        season: ["AUTUMN"],
        weatherCondition: ["CLOUDY", "SUNNY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "ANY",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "autumn street trees berlin",
        tags: ["autumn", "trees", "street", "residential"]
    },
    {
        id: 68,
        title: "Spree Summer Swimming",
        description: "Urban swimming spots along the Spree come alive with summer atmosphere.",
        photographyTips: "Capture diving and swimming action. Afternoon golden light on water. Lifestyle and candid moments.",
        location: "Badeschiff or various Spree spots",
        address: "Eichenstraße 4, 12435 Berlin",
        lat: 52.4935,
        lng: 13.4525,
        mood: ["Energetic", "Social", "Refreshing"],
        season: ["SUMMER"],
        weatherCondition: ["SUNNY"],
        timeOfDay: ["AFTERNOON", "GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1530539595977-5aa0e5d16f42?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "swimming river summer people",
        tags: ["summer", "swimming", "river", "lifestyle"]
    },
    {
        id: 69,
        title: "Spreepark Abandoned Autumn",
        description: "Abandoned amusement park with eerie autumn atmosphere and forgotten structures.",
        photographyTips: "Guided tours only. Autumn fog creates mysterious mood. Telephoto for compressed, cluttered compositions.",
        location: "Spreepark, Plänterwald",
        address: "Kiehnwerderallee 1, 12437 Berlin",
        lat: 52.4761,
        lng: 13.4817,
        mood: ["Mysterious", "Nostalgic", "Eerie"],
        season: ["AUTUMN", "WINTER"],
        weatherCondition: ["FOGGY", "CLOUDY"],
        timeOfDay: ["AFTERNOON"],
        lightDirection: "ANY",
        difficulty: "ADVANCED",
        accessibility: "PERMIT_REQUIRED",
        imageUrl: "https://images.unsplash.com/photo-1509903830954-917f8437b82a?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "abandoned amusement park",
        tags: ["abandoned", "autumn", "mysterious", "urban_exploration"]
    },
    {
        id: 70,
        title: "Outdoor Ice Skating Winter",
        description: "Various outdoor ice rinks create festive winter scenes across the city.",
        photographyTips: "Evening when lights come on. Motion blur of skaters. Wide angle for atmosphere.",
        location: "Various locations (Potsdamer Platz, etc.)",
        address: "Potsdamer Platz, 10785 Berlin",
        lat: 52.5096,
        lng: 13.3756,
        mood: ["Festive", "Energetic", "Winter"],
        season: ["WINTER"],
        weatherCondition: ["ANY", "SNOWY"],
        timeOfDay: ["EVENING", "BLUE_HOUR"],
        lightDirection: "ANY",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1482223882134-1bbb2bdb6a97?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "ice skating winter lights",
        tags: ["winter", "ice_skating", "festive", "evening"]
    },

    // === GOLDEN HOUR SPOTS (10 locations) ===
    {
        id: 71,
        title: "Teufelsberg Sunset Panorama",
        description: "Former spy station with 360-degree views over Berlin and Grunewald forest.",
        photographyTips: "Arrive 1 hour before sunset. Wide panoramas and silhouettes of radar domes. Bring layers - gets windy.",
        location: "Teufelsberg, Grunewald",
        address: "Teufelsseechaussee 10, 14193 Berlin",
        lat: 52.5016,
        lng: 13.2415,
        mood: ["Dramatic", "Atmospheric", "Edgy"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1590425129648-5c4676579e7e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin teufelsberg sunset panorama",
        tags: ["sunset", "panorama", "abandoned", "view"]
    },
    {
        id: 72,
        title: "Klunkerkranich Rooftop Sunset",
        description: "Rooftop bar on parking garage with city views and sunset atmosphere.",
        photographyTips: "Golden hour crowds add atmosphere. Silhouettes against colorful sky. Casual urban lifestyle shots.",
        location: "Neukölln Arcaden Roof, Neukölln",
        address: "Karl-Marx-Straße 66, 12043 Berlin",
        lat: 52.4817,
        lng: 13.4395,
        mood: ["Social", "Urban", "Vibrant"],
        season: ["SPRING", "SUMMER", "AUTUMN"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "rooftop bar sunset people",
        tags: ["rooftop", "sunset", "bar", "social"]
    },
    {
        id: 73,
        title: "Müggelsee Lake Sunrise",
        description: "Berlin's largest lake offers expansive sunrise views over water.",
        photographyTips: "Arrive before sunrise. Long exposure for smooth water. Silhouettes of pier and boats.",
        location: "Müggelsee, Köpenick",
        address: "Müggelseedamm, 12587 Berlin",
        lat: 52.4250,
        lng: 13.6500,
        mood: ["Peaceful", "Serene", "Natural"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["SUNRISE", "BLUE_HOUR"],
        lightDirection: "EAST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "lake sunrise peaceful water",
        tags: ["sunrise", "lake", "nature", "peaceful"]
    },
    {
        id: 74,
        title: "Schlachtensee Forest Lake",
        description: "Forest-ringed lake with wooden pier, perfect for golden hour reflections.",
        photographyTips: "Classic sunset over pier composition. Forest frames the scene. Best on calm evenings.",
        location: "Schlachtensee, Zehlendorf",
        address: "Schlachtensee, 14163 Berlin",
        lat: 52.4350,
        lng: 13.2283,
        mood: ["Peaceful", "Natural", "Romantic"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "forest lake pier sunset",
        tags: ["lake", "sunset", "forest", "pier"]
    },
    {
        id: 75,
        title: "Kreuzberg Hill Monument View",
        description: "Elevated viewpoint with monument offering sunset views over southern Berlin.",
        photographyTips: "Monument silhouette against sunset sky. Wide angle for city panorama. Popular local spot.",
        location: "Viktoriapark, Kreuzberg",
        address: "Kreuzbergstraße, 10965 Berlin",
        lat: 52.4892,
        lng: 13.3820,
        mood: ["Dramatic", "Urban", "Elevated"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin sunset monument view",
        tags: ["sunset", "view", "monument", "panorama"]
    },
    {
        id: 76,
        title: "Wannsee Beach Sunset",
        description: "Lake beach with famous Strandbad, perfect for summer sunset photography.",
        photographyTips: "Beach lifestyle with sunset backdrop. Silhouettes of swimmers and boats. Summer evenings only.",
        location: "Wannsee, Steglitz-Zehlendorf",
        address: "Wannseebadweg 25, 14129 Berlin",
        lat: 52.4206,
        lng: 13.1633,
        mood: ["Relaxed", "Summery", "Golden"],
        season: ["SUMMER", "SPRING", "AUTUMN"],
        weatherCondition: ["SUNNY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "beach sunset summer people",
        tags: ["beach", "sunset", "summer", "lake"]
    },
    {
        id: 77,
        title: "Funkturm Radio Tower Golden Hour",
        description: "1920s radio tower creating dramatic silhouettes at sunset.",
        photographyTips: "Shoot from below for towering perspective. Silhouette against colorful sky. Steel structure details.",
        location: "Messedamm, Charlottenburg",
        address: "Messedamm 22, 14055 Berlin",
        lat: 52.5047,
        lng: 13.2769,
        mood: ["Industrial", "Dramatic", "Historic"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "radio tower sunset silhouette",
        tags: ["tower", "sunset", "industrial", "silhouette"]
    },
    {
        id: 78,
        title: "Lichterfelde West Villas",
        description: "Historic villa district with tree-lined streets perfect for golden hour strolls.",
        photographyTips: "Autumn colors glow in golden hour light. Architectural details on villas. Quiet residential charm.",
        location: "Lichterfelde West, Steglitz-Zehlendorf",
        address: "Hindenburgdamm, 12209 Berlin",
        lat: 52.4378,
        lng: 13.3094,
        mood: ["Elegant", "Peaceful", "Historic"],
        season: ["AUTUMN", "SPRING"],
        weatherCondition: ["SUNNY"],
        timeOfDay: ["GOLDEN_HOUR"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "villa street autumn trees",
        tags: ["architecture", "residential", "autumn", "elegant"]
    },
    {
        id: 79,
        title: "Treptow Arena Spree Sunset",
        description: "Industrial waterfront with sunset over the Spree and Arena Berlin backdrop.",
        photographyTips: "Combine industrial architecture with natural sunset. Boat traffic adds interest. Urban meets nature.",
        location: "Arena Berlin area, Treptow",
        address: "Eichenstraße, 12435 Berlin",
        lat: 52.4935,
        lng: 13.4525,
        mood: ["Industrial", "Atmospheric", "Urban"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "EASY",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1541623089466-8e777dd05d70?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "industrial waterfront sunset",
        tags: ["industrial", "sunset", "river", "urban"]
    },
    {
        id: 80,
        title: "Olympic Stadium Sunset Architecture",
        description: "1936 Olympic Stadium with dramatic Nazi-era architecture silhouetted at sunset.",
        photographyTips: "Strong geometric shapes. Historical context important. Climb bell tower for views (fee).",
        location: "Olympiastadion, Charlottenburg",
        address: "Olympischer Platz 3, 14053 Berlin",
        lat: 52.5147,
        lng: 13.2395,
        mood: ["Dramatic", "Historic", "Powerful"],
        season: ["ALL"],
        weatherCondition: ["SUNNY", "CLOUDY"],
        timeOfDay: ["GOLDEN_HOUR", "SUNSET"],
        lightDirection: "WEST",
        difficulty: "MODERATE",
        accessibility: "PUBLIC",
        imageUrl: "https://images.unsplash.com/photo-1567450560024-8686cd4f47f4?auto=format&fit=crop&w=1000&q=80",
        unsplashQuery: "berlin olympic stadium architecture",
        tags: ["stadium", "historic", "architecture", "sunset"]
    }
];

function getCurrentSeason() {
    const month = new Date().getMonth() + 1;
    if (month >= 3 && month <= 5) return "SPRING";
    if (month >= 6 && month <= 8) return "SUMMER";
    if (month >= 9 && month <= 11) return "AUTUMN";
    return "WINTER";
}

function getCurrentWeather() {
    const conditions = ["SUNNY", "RAINY", "CLOUDY", "SNOWY"];
    return conditions[Math.floor(Math.random() * conditions.length)];
}

module.exports = {
    INSPIRATIONS,
    getCurrentSeason,
    getCurrentWeather
};
